board/urls.py
from django.urls import path

from . import views

app_name = "board"
urlpatterns = [
    path("", views.index, name="index"),
    path("board/<board>", views.board, name="board"),
    path("board/<board>/add_post", views.posting_page, name="posting_page"),
    path(
        "board/<board>/<int:post_id>",
        views.replies_page,
        name="show_replies",
    ),
    path(
        "board/<board>/<int:post_id>/<int:reply_id>",
        views.replies_page,
        name="show_replies_selected",
    ),
    path(
        "board/<board>/<int:post_id>/success",
        views.posting_success,
        name="reply_success",
    ),
    path("board/<board>/<int:post_id>/reply", views.long_reply_page, name="long_reply"),
    path(
        "board/<board>/<int:post_id>/reply/success",
        views.posting_success,
        name="long_reply_success",
    ),
    path("board/<board>/add_post/sucess", views.posting_success, name="post_success"),
    path("board/<board>/<tag>", views.tags_view, name="tag_search"),
]

board/models.py
from django.db import models


class IndexPage(models.Model):
    """acts as a setting for index page."""

    welcome_title = models.CharField(max_length=50)
    welcome_description = models.TextField()
    is_default = models.BooleanField()

    def save(self, *args, **kwargs):
        """make it so only one indexpage can be the default"""
        if self.is_default:
            try:
                temp = IndexPage.objects.get(is_default=True)
                if self != temp:
                    temp.is_default = False
                    temp.save()
            except IndexPage.DoesNotExist:
                pass
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"default: {self.is_default} || {self.welcome_title}"


class Board(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    rules = models.TextField()
    is_default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        """make it so only one board can be the default"""
        if self.is_default:
            try:
                temp = Board.objects.get(is_default=True)
                if self != temp:
                    temp.is_default = False
                    temp.save()
            except Board.DoesNotExist:
                pass
        super().save(*args, **kwargs)

    class Meta:
        constraints = [models.UniqueConstraint(fields=["name"], name="unique board")]

    def tag_count(self):
        return self.tag_set.count()

    def post_count(self):
        return self.post_set.count()

    def __str__(self) -> str:
        return self.name


class Tag(models.Model):
    name = models.SlugField(max_length=15)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    show_in_header = models.BooleanField(
        default=False
    )  # if True the tag will be shown at top of the page as a shortcut

    class Meta:
        ordering = ["name"]

    def post_count(self):
        return self.post_set.count()

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=80, blank=False)
    date_posted = models.DateTimeField(blank=False)
    url = models.URLField(blank=False)
    url_title = models.TextField(max_length=200, blank=False)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, blank=False)
    post_text = models.TextField(max_length=600, blank=False)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ["-date_posted"]

    def relpy_count(self):
        return self.reply_set.count()

    def __str__(self) -> str:
        return self.title


class Reply(models.Model):
    date_posted = models.DateTimeField(blank=False)
    post_text = models.TextField(max_length=600, blank=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=False)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self) -> str:
        return f"{str(self.date_posted)} on {self.post}"

board/forms.py
from django import forms
from django.core.validators import RegexValidator


class PostingForm(forms.Form):
    post_title = forms.CharField(label="Post Title:", max_length=80)
    url = forms.URLField(label="URL:", max_length=100)
    post_message = forms.CharField(
        widget=forms.Textarea(attrs={"name": "body", "rows": 3, "cols": 5}),
        max_length=600,
    )
    tags = forms.CharField(
        label="Tags: (Seperate tags with ',' Like: tag1,tag2)(Maximum 4 tags)",
        max_length=100,
        validators=[
            RegexValidator(
                "^[0-9a-zA-Z]+(,[0-9a-zA-Z]+)*$",
                message="Tags can only be a combination of Alphabets, Numbers & Underscore",
            )
        ],
        required=False,
    )

    def clean(self):
        if len(self.cleaned_data["tags"]) != 0:
            if not self.cleaned_data["tags"].islower():
                raise forms.ValidationError("Tags should be in lowercase")
            if len(self.cleaned_data["tags"].split(",")) > 4:
                raise forms.ValidationError(
                    "Only 4 tags alowed (Make sure you have at most 3 commas in input)"
                )


class QuickReply(forms.Form):
    """Creates an small textinput for writing short replies"""

    post_message = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Write a quick reply"}),
        min_length=1,
        max_length=600,
        label=False,
    )


class LongReply(forms.Form):
    """creates a large textbox for larger replies"""

    post_message = forms.CharField(
        widget=forms.Textarea(),
        min_length=1,
        max_length=600,
        label="Reply message:",
    )

board/views.py
import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from . import get_url_title
from .forms import LongReply, PostingForm, QuickReply
from .models import Board, IndexPage, Post, Reply, Tag


# Create your views here.
def index(request):
    """index page"""
    default_index = IndexPage.objects.get(is_default=True)
    context = {
        "page_title": "Index",
        "page_welcome_note": default_index.welcome_title,
        "header_describtion": default_index.welcome_description,
        "tags": Board.objects.all(),
        "is_index": True,
    }
    return render(request, "board/index.html", context)


def board(request, board):
    """show board first page

    Args:
        board (string): board name

    Returns:
        html: board page with its posts
    """
    board_obj = Board.objects.get(name=board)

    context = {
        "page_title": board_obj.name,
        "page_welcome_note": f"Welcome To The {board_obj.name} Board!",
        "header_describtion": board_obj.desc,
        "tags": board_obj.tag_set.filter(show_in_header=True),
        "posts": board_obj.post_set.all(),
    }
    return render(request, "board/board.html", context=context)


def tags_view(request, board, tag):
    """show all posts containig this tag

    Args:

        board (string): board name
        tag (string): tag name

    Returns:
        html: all posts witch contain this tag
    """
    board_obj = Board.objects.get(name=board)
    context = {
        "page_title": board_obj.name,
        "page_welcome_note": f"Welcome To The {board_obj.name} Board!",
        "header_describtion": board_obj.desc,
        "tags": board_obj.tag_set.filter(show_in_header=True),
        "posts": Tag.objects.get(name=tag).post_set.all(),
        "message": f"Showing results with {tag} tag",
    }
    return render(request, "board/board.html", context=context)


def posting_page(request, board, **kwargs):
    """users can post here

    Args:
        board (string): board name where this posting is going to submit to
    """
    board_obj = Board.objects.get(name=board)
    contex = {
        "page_title": board_obj.name,
        "board_rules": board_obj.rules,
        "result": kwargs.get("results", False),
        "form": PostingForm(),
    }
    if request.method == "POST":
        form = PostingForm(request.POST)
        if form.is_valid():
            post = Post(
                title=form.cleaned_data["post_title"],
                date_posted=timezone.now(),
                url=form.cleaned_data["url"],
                url_title=get_url_title.get_title(form.cleaned_data["url"]),
                post_text=form.cleaned_data["post_message"],
                board=board_obj,
            )
            post.save()

            if len(form.cleaned_data["tags"]) != 0:
                input_tags = form.cleaned_data["tags"].split(",")
                for tag in input_tags:
                    tag = Tag.objects.get_or_create(
                        name=tag, board=board_obj, defaults={"board": board_obj}
                    )
                    post.tags.add(tag[0].id)
            return HttpResponseRedirect(
                reverse("board:show_replies", args=(board_obj.name, post.id))
            )
        else:
            contex["form"] = form
            return render(request, "board/posting_form.html", context=contex)

    else:
        # show posting form
        return render(request, "board/posting_form.html", context=contex)


def posting_success(request, board, post_id, **kwargs):
    """**not implemented yet
    page to show after a post request was successful
    """
    board_obj = Board.objects.get(name=board)
    context = {
        "content": "posting was succesfull",
        "page_title": board_obj.name,
        "post_id": post_id,
    }

    if kwargs.get("is_reply", False):
        context["message"] = "Posting reply was successful"
    else:
        context["message"] = "Posting was successful"
    return render(
        request,
        "board/show_replies.html",
        context=context,
    )


def replies_page(request, board, post_id, **kwargs):
    """show replies to a post, also allows a quick reply

    Args:
        board (string): board name
        post_id (int): post's id

    """
    board_obj = Board.objects.get(name=board)
    post_obj = Post.objects.get(pk=post_id)
    if request.method == "POST":
        form = QuickReply(request.POST)
        if form.is_valid():
            reply = Reply(
                date_posted=timezone.now(),
                post_text=form.cleaned_data["post_message"],
                post=post_obj,
            )
            reply.save()
            return HttpResponseRedirect(
                reverse(
                    "board:show_replies_selected",  # highlight the reply just posted
                    args=(board_obj.name, post_obj.id, reply.id),
                )
            )
    else:
        context = {
            "page_title": board_obj.name,
            "post": post_obj,
            "replies": post_obj.reply_set.all(),
            "form": QuickReply(),
            "board_rules": board_obj.rules,
        }
        reply_id = kwargs.get("reply_id", None)
        if reply_id:
            context["selected_reply"] = Reply.objects.get(pk=reply_id)
        return render(request, "board/replies_page.html", context=context)


def long_reply_page(request, board, post_id):
    """dedicated page for writing long replies

    Args:
        board (string): board name
        post_id (int): id of the post user is replying to
    """
    board_obj = Board.objects.get(name=board)
    post_obj = Post.objects.get(pk=post_id)
    if request.method == "POST":
        form = LongReply(request.POST)
        if form.is_valid():
            reply = Reply(
                date_posted=datetime.datetime.now(),
                post_text=form.cleaned_data["post_message"],
                post=post_obj,
            )
            reply.save()
            return HttpResponseRedirect(
                reverse(
                    "board:show_replies_selected",  # highlight the reply just posted
                    args=(board_obj.name, post_obj.id, reply.id),
                )
            )

    else:
        contex = {
            "page_title": board_obj.name,
            "board_rules": board_obj.rules,
            "form": LongReply(),
        }
        return render(request, "board/posting_form.html", context=contex)

board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="{% static 'board/style.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

{% block styles %}
{% endblock %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <main>
        <header>
            <div class="title">
                <div>
                    <h1 class="title logo"><a href="{% url 'board:index' %}" title="Home">OpenBoard</a></h1>
                </div>
                <div >
                    {% if not is_index %}
                    <h1 class="title page_name"><a href={% url 'board:board' page_title %}>{{ page_title }}</a></h1>
                    {% else %}
                    <h1 class="title page_name">{{ page_title }}</h1>
                    {% endif %}

                </div>
            </div>
            {% block nav %}{% endblock nav %}
        </header>
        {% block page_describtion %}{% endblock page_describtion %}
        <div class="content">
            {% block content %}{% endblock content %}
        </div>

    </main>
</body>

</html>

board/templates/board/board.html
{% extends 'board/base.html' %}
{% block nav %}
<form action="{% url 'board:posting_page' page_title %}">
<button type="submit" onmouseover="">+ Add post</button>
</form>
{% endblock nav %}

{% block page_describtion %}
<div class="board_desc">
    <h1>{{ page_welcome_note }}</h1>
    <div class="desc_note">
        <p>
            {{ header_describtion |safe }}
        </p>
    </div>
    {% if tags %}
    <div class="tags">
        <ul>
            {% for tag in tags %}
            <li><a href="{% url 'board:tag_search' page_title tag.name %}">{{tag}}({{tag.post_count}})</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock page_describtion %}
{% block content %}
{% if message %}
<p class="board_page_message">
    {{ message }}
</p>
{% endif %}
{% if posts %}
    <ul class="posts_list">
        {% for post in posts %}
        <li class="post">
            <div class="post_head">
                <h4>{{ post.date_posted }}</h4>
                <div class="post_topbar">
                    <h2>{{ post.title }}</h2>
                    <form action="{% url 'board:show_replies' page_title post.id %}" class="post_actions">
                        {% csrf_token %}
                        <button onmouseover=""><span class="material-symbols-outlined">
                            inbox
                            </span>
                                {% if post.relpy_count == 0 %}
                                    <p>Add Reply</p>
                                {% else %}
                                <p>{{ post.relpy_count }} Replies</p>
                                {% endif %}
                            </button>
                    </form>
                </div>
            </div>
            <a href="{{ post.url }}" class="post_title_url"><span class="material-symbols-outlined">
                link
                </span> {{ post.url_title }}</a>
            <p>{{ post.post_text }}</p>
            <div class="post_tags">
                <ul>
                    <li>Tags:</li>
                    {% for tag in post.tags.all %}
                    <li><a href="{% url 'board:tag_search' page_title tag.name %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% endfor %}
    </ul>
{% else %}
<p>No posts were found</p>
{% endif %}
{% endblock content %}

board/templates/board/index.html
{% extends 'board/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'board/index_style.css' %}">
<style>
    .content{
        padding:0px !important;
    }
</style>
{% endblock %}
{% block page_describtion %}
<div class="board_desc">
    <h1>{{ page_welcome_note }}</h1>
    <div class="desc_note">
        <p>
            {{ header_describtion |safe }}
        </p>
    </div>
    {% if tags %}
    <div class="tags">
        <ul>
            {% for tag in tags %}
            <li><a href="{% url 'board:board' tag.name %}">{{tag}}({{tag.post_count}})</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock page_describtion %}
{% block content %}
{% endblock content %}

board/templates/board/posting_form.html
{% extends 'board/base.html' %}
{% block content %}
{% if result %}
<p>{{ result }}</p>
{% else %}
<dev class="posting_section">
<dev class="rules">
    <h3>{{ page_title }} Board rules:</h3>
    {{board_rules|safe}}
</dev>
<form id="posting_form" class="posting_form" method="post">
    {% csrf_token %}
    {{ form }}
    <p></p>
    <button type="submit" form="posting_form">Submit</button>
</form>
</dev>
{% endif %}
{% endblock content %}

board/templates/board/replies_page.html
{% extends 'board/base.html' %}
{% block nav %}
<form action="{% url 'board:posting_page' page_title %}">
<button type="submit" onmouseover="">+ Add post</button>
</form>
{% endblock nav %}
{% block content %}
{% if post %}
    <ul class="posts_list reply_section">
        <li class="post">
            <div class="post_head">
                <h4>{{ post.date_posted }}</h4>
                <div class="post_topbar">
                    <h2>{{ post.title }}</h2>
                </div>
            </div>
            <a href="{{ post.url }}" class="post_title_url"><span class="material-symbols-outlined">
                link
                </span> {{ post.url_title }}</a>
            <p>{{ post.post_text }}</p>
            <div class="post_tags">
                <ul>
                    <li>Tags:</li>
                    {% for tag in post.tags.all %}
                    <li><a href="{% url 'board:tag_search' page_title tag.name %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <dev class="rules">
                <h3>{{ page_title }} Board rules:</h3>
                {{board_rules|safe}}
            </dev>
            <ul style="padding-left: 0;">
                {% for relpy in replies %}
                    {% if relpy == selected_reply %}
                        <li class="post reply selceted">
                    {% else %}
                        <li class="post reply">
                    {% endif %}
                            <div class="post_head">
                                <h4>{{ relpy.date_posted }}</h4>
                            </div>
                            <p>{{ relpy.post_text }}</p>
                        </li>
                {% endfor %}
                </ul>
        </li>

    </ul>
{% else %}
<p>post was not found</p>
{% endif %}
<div class="reply_box">
    <form action="{% url 'board:long_reply' page_title post.id %}">
        {% csrf_token %}
        <button type="submit" onmouseover="" class="expand">
        <span class="material-symbols-outlined" style="padding: 0;">open_in_full</span>
        </button>
    </form>
    <div class="reply_message" style="width: 100%;">
        <form style="width: -webkit-fill-available;" class="reply_input" id="reply_form" method="post">
            {% csrf_token %}
            {{ form }}
            </form>
    </div>

    <button type="submit" onmouseover="" form="reply_form"><span class="material-symbols-outlined" style="padding: 0;">send</span></button>



</div>
{% endblock content %}

board/templates/board/success_page.html
{% extends 'board/base.html' %}
{% block content %}
<div class="alert">
    <div class="message">
        <p>{{ message }}</p>
    </div>
    <form action="{% url 'board:show_replies' page_title post_id %}">
        <button type="submit" onmouseover="">Take me to the post</button>
        </form>
</div>
{% endblock content %}